<?php
echo '{
	"status": "0010160009",
	"obj": {
		"weixinQrcodeDisplay": 0,
		"qq2": "",
		"qq1": "",
		"taobaoLinkDisplay": 0,
		"qq2Display": 0,
		"weixinPublicQrcode": "",
		"cxEnableAdd": 1,
		"version": 1,
		"cxAddUrl": "http://49.233.162.4:6868/add",
		"id": 18,
		"cxQueryUrl": "http://106.15.204.69:6868/userCx",
		"qq1Display": 0,
		"title": "迷你网课系统",
		"copyRight": "Copyright ©2015-2020 nanashuake.com All Rights Reserved <a href=\"http://www.beian.miit.gov.cn/\" target=\"_blank\" style=\"margin:0 5px;\">陕ICP备18018130号-1<\/a>",
		"loginBg": "",
		"zhsEnableAdd": 1,
		"description": "",
		"userId": 43,
		"domain": "nanashuake.com",
		"partner": "",
		"notice": "此网站抄袭的娜娜网站，之所以这样做，是因为方便，还能蹭热度，还有可能被脑瘫当做是娜娜作者</br></br>如果你觉得我是娜娜作者，那我就是，请尽快打钱，我给你开客户端。",
		"zfbQrcodeDisplay": 0,
		"redirectUrl": "",
		"key": "",
		"weixinQrcode": "",
		"logo": "",
		"weixinPublicQrcodeDisplay": 0,
		"domainSuffix": "",
		"privateKey": "",
		"qqQunLink": "",
		"websiteHelpInfo": "",
		"weidianLinkDisplay": 0,
		"zhsAddUrl": "http://49.233.162.4:6869/add",
		"domain2": "wk.nanashuake.com",
		"color": "",
		"qqQun": "",
		"zfbQrcode": "",
		"taobaoLink": "",
		"subdomain": "",
		"payType": 0,
		"qqQunDisplay": 0,
		"weidianLink": ""
	},
	"code": 20000,
	"success": true,
	"msg": "成功"
}';
?>